import React from 'react';
import ReactDOM from 'react-dom';
import { Provider } from 'react-redux';
import { createStore } from 'redux';
import reducer from './reducers/index';
import App from './routes/App';

const initialState = {
  'user': {},
  'myfav': [],
  'boards': [
    {
      'id': 2,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'Z490 Aorus Xtreme Waterforce',
      'compatibility': 'intel',
      'ddr': '4',
      'year': 2009,
      'image': 'https://static.gigabyte.com/Product/2/7249/2020043017292972629c53754fd600e173884f0c287d18f6_m.png',
      'description': 'Intel® Z490 AORUS Motherboard with 16+1 Phases Digital VRM, AORUS All-In-One Monoblock ,NanoCarbon Baseplate, Intel® Thunderbolt 3, ESSential USB DAC, Intel® WiFi 6 802.11ax, AQUANTIA® 10GbE LAN, Intel® 2.5GbE LAN, RGB FAN COMMANDER',
    },
    {
      'id': 3,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'B550 AORUS MASTER',
      'compatibility': 'intel',
      'ddr': '4',
      'year': 2009,
      'image': 'https://static.gigabyte.com/Product/2/7425/2020052114370686011ad28522a1fb9c0575f75dd129001c_m.png',
      'description': 'AMD B550 AORUS Motherboard with Direct 16 Phases Digital VRM, Fins-Array Heatsink, Direct-Touch Heatpipe, Thermal Backplate, Triple PCIe 4.0 x4 M.2 Direct from CPU, Intel® WiFi 6 802.11ax, 2.5GbE LAN, RGB FUSION 2.0, Q-Flash Plus',
    },
    {
      'id': 4,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'X399 GAMING PRO CARBONO AC',
      'compatibility': 'amd',
      'ddr': '4',
      'year': 2009,
      'image': 'https://static.gigabyte.com/Product/2/7425/2020052114370686011ad28522a1fb9c0575f75dd129001c_m.png',
      'description': 'Supports AMD® RYZEN™ THREADRIPPER™ Series Processors',
    },
    {
      'id': 5,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'MPG B550 GAMING EDGE WIFI',
      'compatibility': 'amd',
      'ddr': '4',
      'year': 2009,
      'image': 'https://storage-asset.msi.com/global/picture/image/feature/mb/B550/MPG/edge-wifi/story_img.png',
      'description': 'Supports AMD® RYZEN™ THREADRIPPER™ Series Processors',
    },
  ],
  'cpus': [
    {
      'id': 6,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'Intel Core i7-9700K',
      'compatibility': 'intel',
      'ddr': '4',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/71Q5sdPHD-L._AC_SL1500_.jpg',
      'description': 'Intel Core i7-9700K - Procesador de escritorio (8 núcleos, hasta 4.9 GHz, Turbo desbloqueado, LGA1151 300 Series, 95 W)',
    },
    {
      'id': 7,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'Procesador Intel Core i9-10900X',
      'compatibility': 'intel',
      'ddr': '4',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/61mBrF1jNuL._AC_SL1500_.jpg',
      'description': 'Procesador Intel Core i9-10900X de sobremesa 10 núcleos de hasta 4,7 GHz desbloqueado LGA2066 serie X299 165W (BX8069510900X)',
    },
    {
      'id': 8,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'AMD Ryzen 9 3900X',
      'compatibility': 'amd',
      'ddr': '4',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/71S31CWSs3L._AC_SL1093_.jpg',
      'description': 'AMD Ryzen 9 3900X 12-core, 24-thread desbloqueado procesador de escritorio',
    },
    {
      'id': 9,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'AMD Ryzen Threadripper 3970X',
      'compatibility': 'amd',
      'ddr': '4',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/81D-WvtG6OL._AC_SL1500_.jpg',
      'description': 'AMD Ryzen Threadripper 3970X Procesador de escritorio desbloqueado de 32 núcleos, 64 hilos, sin refrigerador',
    },
  ],
  'memory': [
    {
      'id': 10,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'G.SKILL TridentZ RGB Series 16GB',
      'compatibility': 'any',
      'ddr': '4',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/61Mo5QjeXwL._AC_SL1062_.jpg',
      'description': 'G.SKILL TridentZ RGB Series 16GB (2 x 8GB) 288-Pin DDR43200MHz (PC4 25600) memoria de escritorio modelo F4-3200C16D-16GTZR',
    },
    {
      'id': 11,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'Corsair Dominator Platinum RGB',
      'compatibility': 'any',
      'ddr': '4',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/7138EcrSh7L._AC_SL1500_.jpg',
      'description': 'Corsair Dominator Platinum RGB - Memoria de sobremesa, Negro',
    },
  ],
  'gpus': [
    {
      'id': 12,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'MSI Gaming GeForce RTX 2080 Super 8GB GDRR6',
      'compatibility': 'any',
      'ddr': '6',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/81WhZNCowVL._AC_SL1500_.jpg',
      'description': 'MSI Gaming GeForce RTX 2080 Super 8GB GDRR6 256 Bit HDMI/DP Nvlink Tri-Frozr Turing Architecture Tarjeta gráfica overclocked (RTX 2080 Super Gaming X Trio)',
    },
    {
      'id': 13,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'Gigabyte Gv-R57XTGAMING OC-8GD Radeon Rx 5700 Xt',
      'compatibility': 'any',
      'ddr': '6',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/81RnIUgJnCL._AC_SL1500_.jpg',
      'description': 'Gigabyte Gv-R57XTGAMING OC-8GD Radeon Rx 5700 Xt Gaming OC 8G tarjeta gráfica, PCIe 4.0, 8GB 256-Bit GDDR6, tarjeta de vídeo',
    },
  ],
  'powerSupply': [
    {
      'id': 14,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'EVGA Supernova 550w',
      'compatibility': 'any',
      'ddr': 'any',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/71pul5O6iZL._AC_SL1500_.jpg',
      'description': 'EVGA Supernova 220-G2-0550-Y1 Fuente de alimentación totalmente modular',
    },
    {
      'id': 15,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'Fuente de alimentación 750 W totalmente modular 80 + oro',
      'compatibility': 'any',
      'ddr': 'any',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/71ptS2qPRhL._AC_SL1468_.jpg',
      'description': 'Fuente de alimentación 750 W totalmente modular 80 + oro certificado con luz RGB direccionable - Modo de color Vairous, GAMEMAX RGB750-Rainbow',
    },
    {
      'id': 16,
      'priceUs': 250,
      'priceCop': 750000,
      'model': 'EVGA Supernova P2 Fuente de alimentación 80PLUS Platinum 1000w',
      'compatibility': 'any',
      'ddr': 'any',
      'year': 2009,
      'image': 'https://images-na.ssl-images-amazon.com/images/I/71O6tFHFGQL._AC_SL1200_.jpg',
      'description': 'EVGA Supernova P2 Fuente de alimentación 80PLUS Platinum Certificado ATX Fuente de alimentación',
    },
  ],
};

const store = createStore(reducer, initialState);

ReactDOM.render(
  <Provider store={store}>
    <App />
  </Provider>,
  document.getElementById('app'),
);
